baseURL = 'http://localhost:3000/'
languageCode = 'en-us'
title = 'Task Management'

[taxonomies]
  subject = "subject"  
  grade = "grade"
  classification = "classification"

[permalinks]
  subject = "/subjects/:slug/"  
  grade = "/grades/:slug/"
